---
env:
  es2020: true
ignorePatterns:
  - "coverage"
  - "node_modules"
  - "**/*.d.ts"
overrides:
  - files:
      - "*.ts"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project:
        - ./tsconfig.json
    plugins:
      - "@typescript-eslint"
    rules:
      node/no-unsupported-features/es-syntax: off
    settings:
      node:
        tryExtensions:
          - ".ts"
          - ".tsx"
          - ".js"
          - ".json"
    env:
      node: true
      jest/globals: true
    extends:
      - eslint:recommended
      - plugin:node/recommended
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:jest/recommended
      - plugin:prettier/recommended
      - prettier/@typescript-eslint
